/*
 * Muhammad Faisal Amir
 * f.miir117@gmail.com
 * id.amirisback.bandung
 * Copyright 2017
 */
package dnb;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Faisal Amir
 */
public class daerah extends javax.swing.JFrame {
    connection conn = new connection();
    private String sql = "";
    private String id_pulau = "";
    private int lebar, tinggi;
    private Object get_username;
    /**
     * Creates new form index
     */
    public daerah(Object get_username) {
        this.get_username=get_username;
        initComponents();
        conn.ConnectToDB();
        resizeImage();
        showNama();
    }
    
    private daerah(){
    }
    
    public void showNama(){
        try {
            sql = "Select * From data_akun where username = '"+get_username+"'";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            while (conn.getResultSet().next()){
                txt_nama.setText(conn.getResultSet().getString("nama"));
            }
        } catch (Exception e) {
        }
    }
    
    public void resizeImage(){
        try {
            File foto = new File("../dnb/src/dnb/Icon/peta.png");
            BufferedImage imgUkuranAsli = ImageIO.read(foto);
            lebar = panel_gambar.getWidth();
            tinggi = panel_gambar.getHeight();
            BufferedImage imgResize = new BufferedImage(lebar, tinggi, BufferedImage.TYPE_INT_ARGB);
            Graphics2D imgTampil = imgResize.createGraphics();
            imgTampil.drawImage(imgUkuranAsli, 0, 0, lebar, tinggi, null);
            imgTampil.dispose();
            ImageIcon ImgOut = new ImageIcon(imgResize);
            gambar.setText("");
            gambar.setIcon(ImgOut);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel_gambar = new javax.swing.JPanel();
        btn_jawa = new javax.swing.JLabel();
        btn_sumatra = new javax.swing.JLabel();
        btn_papua = new javax.swing.JLabel();
        btn_nusatenggara = new javax.swing.JLabel();
        btn_kalimantan = new javax.swing.JLabel();
        btn_sulawesi = new javax.swing.JLabel();
        btn_bali = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();
        Halo = new javax.swing.JLabel();
        txt_nama = new javax.swing.JLabel();
        Halo1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel2.setText("Dapur Nusantara Bunda");

        jLabel3.setText("Copyright || Dapur Nusantara Bunda 2017");

        jPanel3.setBackground(new java.awt.Color(255, 248, 206));

        panel_gambar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_jawa.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_jawa.setForeground(new java.awt.Color(255, 0, 0));
        btn_jawa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_jawa.setText("X");
        btn_jawa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jawaMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_jawa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 40));

        btn_sumatra.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_sumatra.setForeground(new java.awt.Color(255, 0, 0));
        btn_sumatra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sumatra.setText("X");
        btn_sumatra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sumatraMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_sumatra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 40));

        btn_papua.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_papua.setForeground(new java.awt.Color(255, 0, 0));
        btn_papua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_papua.setText("X");
        btn_papua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_papuaMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_papua, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, 40));

        btn_nusatenggara.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_nusatenggara.setForeground(new java.awt.Color(255, 0, 0));
        btn_nusatenggara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nusatenggara.setText("X");
        btn_nusatenggara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nusatenggaraMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_nusatenggara, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, 40));

        btn_kalimantan.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_kalimantan.setForeground(new java.awt.Color(255, 0, 0));
        btn_kalimantan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_kalimantan.setText("X");
        btn_kalimantan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kalimantanMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_kalimantan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 40));

        btn_sulawesi.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_sulawesi.setForeground(new java.awt.Color(255, 0, 0));
        btn_sulawesi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sulawesi.setText("X");
        btn_sulawesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sulawesiMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_sulawesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 40));

        btn_bali.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_bali.setForeground(new java.awt.Color(255, 0, 0));
        btn_bali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_bali.setText("X");
        btn_bali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_baliMouseClicked(evt);
            }
        });
        panel_gambar.add(btn_bali, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 40));

        gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar.setText("jLabel1");
        panel_gambar.add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 873, 377));

        Halo.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Halo.setText("Halo,");

        txt_nama.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txt_nama.setText("Nama");

        Halo1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Halo1.setText("|| Silahkan Memilih Pulau");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Halo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Halo1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Halo)
                        .addComponent(txt_nama))
                    .addComponent(Halo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_gambar, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sumatraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumatraMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_SUMATRA";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sumatraMouseClicked

    private void btn_kalimantanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kalimantanMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_KALIMANTAN";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kalimantanMouseClicked

    private void btn_jawaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jawaMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_JAWA";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jawaMouseClicked

    private void btn_sulawesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sulawesiMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_SULAWESI";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sulawesiMouseClicked

    private void btn_papuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_papuaMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_PAPUA";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_papuaMouseClicked

    private void btn_nusatenggaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nusatenggaraMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_NT";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nusatenggaraMouseClicked

    private void btn_baliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_baliMouseClicked
        // TODO add your handling code here:
        id_pulau = "IDP_BALI";
        list_masakan_user lsu = new list_masakan_user(id_pulau);
        lsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_baliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daerah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Halo;
    private javax.swing.JLabel Halo1;
    private javax.swing.JLabel btn_bali;
    private javax.swing.JLabel btn_jawa;
    private javax.swing.JLabel btn_kalimantan;
    private javax.swing.JLabel btn_nusatenggara;
    private javax.swing.JLabel btn_papua;
    private javax.swing.JLabel btn_sulawesi;
    private javax.swing.JLabel btn_sumatra;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_gambar;
    private javax.swing.JLabel txt_nama;
    // End of variables declaration//GEN-END:variables
}
